apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc

  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.23.0

    - repoURL: <YOUR_GIT_REPO_URL>
      targetRevision: main
      ref: values

  source:
    helm:
      valueFiles:
        - $values/apps/istio/istio-values/istiod-values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
