apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc

  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.23.0

    - repoURL: https://github.com/kiprotichgidii/istio-gitops.git
      targetRevision: main
      ref: values

  source:
    helm:
      valueFiles:
        - $values/apps/istio/istio-values/gateway-values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
