apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # CRDs first
    argocd.argoproj.io/tracking-id: istio-stack:argoproj.io/Application:argocd/istio-base
spec:
  project: default
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc

  sources:
    # 1. Helm chart from Istio
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.23.0
      helm:
        valueFiles:
          - $values/apps/istio/istio-values/base-values.yaml

    # 2. Values from your Git repo
    - repoURL: https://github.com/kiprotichgidii/istio-gitops.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
