apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/tracking-id: istio-stack:argoproj.io/Application:argocd/istio-ingress-gateway
spec:
  project: default
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc

  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.23.0
      helm:
        valueFiles:
          - $values/apps/istio/istio-values/gateway-values.yaml

    - repoURL: https://github.com/kiprotichgidii/istio-gitops.git
      targetRevision: main
      ref: values
      
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
